SET(LIBNFC_DRIVER_ACR122 ON CACHE BOOL "Enable ACR122 support (Depends on PC/SC)")
SET(LIBNFC_DRIVER_PN531_USB ON CACHE BOOL "Enable PN531_USB support (Depends on libusb)")
SET(LIBNFC_DRIVER_PN533_USB ON CACHE BOOL "Enable PN533_USB support (Depends on libusb)")
SET(LIBNFC_DRIVER_ARYGON ON CACHE BOOL "Enable ARYGON support (Use serial port)")
SET(LIBNFC_DRIVER_PN532_UART OFF CACHE BOOL "Enable PN533_USB support (Use serial port)")

IF(LIBNFC_DRIVER_ACR122)
  ADD_DEFINITIONS("-DDRIVER_ACR122_ENABLED")
ENDIF(LIBNFC_DRIVER_ACR122)

IF(LIBNFC_DRIVER_PN531_USB)
  ADD_DEFINITIONS("-DDRIVER_PN531_USB_ENABLED")
ENDIF(LIBNFC_DRIVER_PN531_USB)

IF(LIBNFC_DRIVER_PN533_USB)
  ADD_DEFINITIONS("-DDRIVER_PN533_USB_ENABLED")
ENDIF(LIBNFC_DRIVER_PN533_USB)

IF(LIBNFC_DRIVER_ARYGON)
  ADD_DEFINITIONS("-DDRIVER_ARYGON_ENABLED")
ENDIF(LIBNFC_DRIVER_ARYGON)

IF(LIBNFC_DRIVER_PN532_UART)
  ADD_DEFINITIONS("-DDRIVER_PN532_UART_ENABLED")
ENDIF(LIBNFC_DRIVER_PN532_UART)
