.TH NFC-SAM 1 "June 15, 2010"
.SH NAME
nfc-sam \- NFC SAM comunication command line tool based on libnfc
.SH SYNOPSIS
.B nfc-sam
.SH DESCRIPTION
.B nfc-sam
utility attempts to test a simple connection with a SAM (Secure Access Module) in several modes.

To run this utility you must have a SAM (like the NXP's P5CN072 chip) successfully connected to your NFC chip.

.SH BUGS
Please report any bugs on the
.B libnfc
forum at
.BR http://www.libnfc.org/community/ "."
.SH LICENCE
.B libnfc
and
.B libnfc-examples
are covered by the GNU Lesser General Public License (LGPL), version 3.
.SH AUTHORS
Roel Verdult <roel@libnfc.org>
.PP
This manual page was written by Emanuele Bertoldi <zuck@fastwebnet.it>.
It is licensed under the terms of the GNU GPL (version 2 or later).
