.TH nfc-dep-initiator 1 "October 8, 2010" "libnfc" "libnfc's examples"
.SH NAME
nfc-dep-initiator \- Demonstration tool to send/received data as D.E.P. initiator
.SH SYNOPSIS
.B nfc-dep-initiator
.SH DESCRIPTION
.B nfc-dep-initiator
is a demonstration tool for putting NFC device in D.E.P. initiator mode.

This example will attempt to select a passive D.E.P. target and exchange a
simple "Hello" data with target.

Note: this example is designed to work with a D.E.P. target driven by
\fBnfc-dep-target\fP

.SH BUGS
Please report any bugs on the
.B libnfc
issue tracker at:
.br
.BR http://code.google.com/p/libnfc/issues
.SH LICENCE
.B libnfc
is licensed under the GNU Lesser General Public License (LGPL), version 3.
.br
.B libnfc-utils
and
.B libnfc-examples
are covered by the the BSD 2-Clause license.
.SH AUTHORS
Roel Verdult <roel@libnfc.org>, 
.br
Romuald Conty <romuald@libnfc.org>.
.PP
This manual page was written by Romuald Conty <romuald@libnfc.org>.
It is licensed under the terms of the GNU GPL (version 2 or later).
