.TH nfc-dep-target 1 "October 8, 2010" "libnfc" "libnfc's examples"
.SH NAME
nfc-dep-target \- Demonstration tool to send/received data as D.E.P. target
.SH SYNOPSIS
.B nfc-dep-target
.SH DESCRIPTION
.B nfc-dep-target
is a demonstration tool for putting NFC device in D.E.P. target mode.

This example will listen for a D.E.P. initiator and exchange a simple "Hello"
data with initiator.

Note: this example is designed to work with a D.E.P. initiator driven by
\fBnfc-dep-initiator\fP.

.SH BUGS
Please report any bugs on the
.B libnfc
issue tracker at:
.br
.BR http://code.google.com/p/libnfc/issues
.SH LICENCE
.B libnfc
is licensed under the GNU Lesser General Public License (LGPL), version 3.
.br
.B libnfc-utils
and
.B libnfc-examples
are covered by the the BSD 2-Clause license.
.SH AUTHORS
Roel Verdult <roel@libnfc.org>, 
.br
Romuald Conty <romuald@libnfc.org>.
.PP
This manual page was written by Romuald Conty <romuald@libnfc.org>.
It is licensed under the terms of the GNU GPL (version 2 or later).
