.TH NFC-POLL 1 "June 26, 2009"
.SH NAME
nfc-poll \- Poll for one NFC target
.SH SYNOPSIS
.B nfc-poll
.SH DESCRIPTION
.B nfc-poll
is a utility for polling any available target (tags but also NFCIP targets)
using ISO14443-A, FeliCa, Jewel and ISO14443-B modulations.

This tool relies on a hardware polling feature of the PN532, it will display
available information retrieved from the tag.

.SH BUGS
Please report any bugs on the
.B libnfc
forum at
.BR http://www.libnfc.org/community/ "."
.SH LICENCE
.B libnfc
and
.B libnfc-examples
are covered by the GNU Lesser General Public License (LGPL), version 3.
.SH AUTHORS
Romuald Conty <romuald@libnfc.org>>
.PP
This manual page was written by Romuald Conty <romuald@libnfc.org>>.
It is licensed under the terms of the GNU GPL (version 2 or later).
