.TH pn53x-sam 1 "June 15, 2010" "libnfc" "libnfc's examples"
.SH NAME
pn53x-sam \- PN53x SAM communication demonstration tool
.SH SYNOPSIS
.B pn53x-sam
.SH DESCRIPTION
.B pn53x-sam
is a utility attempt to test a simple connection with a SAM (Secure Access
Module) in several modes.

To run this utility you must have a SAM (like the NXP's P5CN072 chip)
successfully connected to your PN53x chip.

Warning: the SAM inside a Touchatag/ACR122U  is \fInot\fP hooked to the PN532
but to the intermediate controller so \fBpn53x-sam\fP won't work with a Touchatag/ACR122U.

.SH BUGS
Please report any bugs on the
.B libnfc
issue tracker at:
.br
.BR http://code.google.com/p/libnfc/issues
.SH LICENCE
.B libnfc
is licensed under the GNU Lesser General Public License (LGPL), version 3.
.br
.B libnfc-utils
and
.B libnfc-examples
are covered by the the BSD 2-Clause license.
.SH AUTHORS
Emanuele Bertoldi <emanuele.bertoldi@gmail.com>
.PP
This manual page was written by Emanuele Bertoldi <emanuele.bertoldi@gmail.com>.
It is licensed under the terms of the GNU GPL (version 2 or later).
