.TH pn53x-diagnose 1 "June 15, 2010" "libnfc" "libnfc's examples"
.SH NAME
pn53x-diagnose \- PN53x diagnose tool
.SH SYNOPSIS
.B pn53x-diagnose
.SH DESCRIPTION
.B pn53x-diagnose
is a utility to diagnose PN531, PN532 and PN533 chips.
It runs communication, RAM and ROM tests.

.SH BUGS
Please report any bugs on the
.B libnfc
issue tracker at:
.br
.BR http://code.google.com/p/libnfc/issues
.SH LICENCE
.B libnfc
is licensed under the GNU Lesser General Public License (LGPL), version 3.
.br
.B libnfc-utils
and
.B libnfc-examples
are covered by the the BSD 2-Clause license.
.SH AUTHORS
Romuald Conty <romuald@libnfc.org>
.PP
This manual page was written by Romuald Conty <romuald@libnfc.org>.
It is licensed under the terms of the GNU GPL (version 2 or later).
