.TH pn53x-tamashell 1 "September 15, 2010"
.SH NAME
pn53x-tamashell \- PN53x TAMA communication demonstration shell
.SH SYNOPSIS
.B pn53x-tamashell
.IR [script]
.SH DESCRIPTION
.B pn53x-tamashell
is a simple interactive tool to send so called TAMA commands
and receive the answers.
TAMA refers to the command set supported by the PN53x family.
Messages are binary and the shell expects hexadecimal notation.
TAMA commands and responses prefixes (0xD4/0xD5), CRC and any framing above are handled transparently.

You can use the shell interactively (with readline support) or you
can write your own script file consisting in commands and
comments (anything that starts with ";", "#" or "//").
Spaces are ignored and can be used for readability.

Shebang is supported, simply start your script with:
 #!/usr/bin/env \fBpn53x-tamashell\fP

.SH COMMANDS

\fIp N\fP to introduce a pause of N milliseconds.

\fIq\fP or \fICtrl-d\fP to quit.

.SH EXAMPLES

GetFirmware command is D4 02, so one has just to send the command "02":

 $ \fBpn53x-tamashell\fP
 Connected to NFC reader: SCM Micro/SCL3711-NFC&RW - PN533 v2.7 (0x07)
 > 02
 Tx: 02
 Rx: 33  02  07  07
 > 40
 Tx: 40
 Rx: Command Not Acceptable
 > q
 Bye!

Same thing, with a script:

 $ \fBpn53x-tamashell\fP << EOF
 // This is a comment
 02 // GetFirmware
 40 // Command with missing arguments
 EOF

 Connected to NFC reader: SCM Micro/SCL3711-NFC&RW - PN533 v2.7 (0x07)
 > // This is a comment
 > 02 // GetFirmware
 Tx: 02
 Rx: 33  02  07  07
 > 40 // Command with missing arguments
 Tx: 40
 Rx: Command Not Acceptable
 > Bye!

.SH OPTIONS
.IR script
Script file with tama commands

.SH BUGS
Please report any bugs on the
.B libnfc
issue tracker at:
.br
.BR http://code.google.com/p/libnfc/issues
.SH LICENCE
.B libnfc
is licensed under the GNU Lesser General Public License (LGPL), version 3.
.br
.B libnfc-utils
and
.B libnfc-examples
are covered by the the BSD 2-Clause license.
.PP
This manual page is licensed under the terms of the GNU GPL (version 2 or later).
