.TH PN53X-DIAGNOSE 1 "June 15, 2010"
.SH NAME
pn53x-diagnose \- PN53x diagnose tool
.SH SYNOPSIS
.B pn53x-diagnose
.SH DESCRIPTION
.B pn53x-diagnose
is a utility to diagnose PN531, PN532 and PN533 chips.
It runs communication, RAM and ROM tests.

.SH BUGS
Please report any bugs on the
.B libnfc
forum at
.BR http://www.libnfc.org/community/ "."
.SH LICENCE
.B libnfc
and
.B libnfc-examples
are covered by the GNU Lesser General Public License (LGPL), version 3.
.SH AUTHORS
Romuald Conty <romuald@libnfc.org>
.PP
This manual page was written by Romuald Conty <romuald@libnfc.org>.
It is licensed under the terms of the GNU GPL (version 2 or later).
