.TH nfc-read-forum-tag3 1 "November 22, 2011" "libnfc" "NFC Utilities"
.SH NAME
nfc-read-forum-tag3 \- Extract NDEF Message from a NFC Forum Tag Type 3
.SH SYNOPSIS
.B nfc-read-forum-tag3
.RI \fR\fB\-o\fR
.IR FILE 
.SH DESCRIPTION
.B nfc-read-forum-tag3
This utility extracts (if available) NDEF Messages contained in a NFC Forum Tag Type 3 to
.IR FILE
.
.SH OPTIONS
\fR\fB\-o\fR 
output extracted NDEF Message to
.IR FILE

.SH BUGS
Please report any bugs on the
.B libnfc
issue tracker at:
.br
.BR http://code.google.com/p/libnfc/issues
.SH LICENCE
.B libnfc
is licensed under the GNU Lesser General Public License (LGPL), version 3.
.br
.B libnfc-utils
and
.B libnfc-examples
are covered by the the BSD 2-Clause license.
.SH AUTHORS
Roel Verdult <roel@libnfc.org>, 
.br
Romain Tartière <romain@libnfc.org>, 
.br
Romuald Conty <romuald@libnfc.org>.
.PP
This manual page was written by Audrey Diacre <adiacre@il4p.fr>.
It is licensed under the terms of the GNU GPL (version 2 or later).