.TH nfc-list 1 "June 26, 2009" "libnfc" "NFC Utilities"
.SH NAME
nfc-list \- list NFC targets
.SH SYNOPSIS
.B nfc-list
[
.I options
]
.SH DESCRIPTION
.B nfc-list
is a utility for listing any available tags like ISO14443-A, FeliCa, Jewel
or ISO14443-B (according to the device capabilities).
It may detect several tags at once thanks to a mechanism called anti-collision
but all types of tags don't support anti-collision and there is some physical
limitation of the number of tags the reader can discover.

This tool displays all available information at selection time.

.SH OPTIONS
.TP
.B \-v
Tells
.I
nfc-list
to be verbose and display detailed information about the targets shown.
This includes SAK decoding and fingerprinting is available.
.TP
\fB-t\fP \fIX\fP
Polls only for types according to bitfield value of \fIX\fP:
   1: ISO14443A
   2: Felica (212 kbps)
   4: Felica (424 kbps)
   8: ISO14443B
  16: ISO14443B'
  32: ISO14443B-2 ST SRx
  64: ISO14443B-2 ASK CTx
 128: Jewel

So 255 (default) polls for all types.

Note that if 16, 32 or 64 then 8 is selected too.

.SH EXAMPLE
For an ISO/IEC 14443-A tag (i.e.Mifare DESFire):

    ATQA (SENS_RES): 03  44  
       UID (NFCID1): 04  45  35  01  db  24  80  
      SAK (SEL_RES): 20  
          ATS (ATR): 75  77  81  02  80  

.SH BUGS
Please report any bugs on the
.B libnfc
issue tracker at:
.br
.BR http://code.google.com/p/libnfc/issues
.SH LICENCE
.B libnfc
is licensed under the GNU Lesser General Public License (LGPL), version 3.
.br
.B libnfc-utils
and
.B libnfc-examples
are covered by the the BSD 2-Clause license.
.SH AUTHORS
Roel Verdult <roel@libnfc.org>, 
.br
Romain Tartière <romain@libnfc.org>, 
.br
Romuald Conty <romuald@libnfc.org>.
.PP
This manual page was written by Romuald Conty <romuald@libnfc.org>.
It is licensed under the terms of the GNU GPL (version 2 or later).
