.TH nfc-barcode 1 "May, 2017" "libnfc" "libnfc's examples"
.SH NAME
nfc-barcode \- NFC Barcode (Tag-Talks-First) reader
.SH SYNOPSIS
.B nfc-barcode
.SH DESCRIPTION
.B nfc-barcode
is a utility to read and decode NFC Barcodes

.SH OPTIONS
.B -d
Decode content, if possible.

.B -v
Verbose.

.SH BUGS
Please report any bugs on the
.B libnfc
issue tracker at:
.br
.BR https://github.com/nfc-tools/libnfc/issues
.SH LICENCE
.B libnfc
is licensed under the GNU Lesser General Public License (LGPL), version 3.
.br
.B libnfc-utils
and
.B libnfc-examples
are covered by the the BSD 2-Clause license.
.SH AUTHORS
Philippe Teuwen <yobibe@gmail.com>
.PP
This manual page was written by Philippe Teuwen <yobibe@gmail.com>.
It is licensed under the terms of the GNU GPL (version 2 or later).
