.TH nfc-emulate-forum-tag2 1 "November 22, 2011" "libnfc" "NFC Utilities"
.SH NAME
nfc-emulate-forum-tag2 \- NFC Forum tag type 2 emulation command line demonstration tool
.SH SYNOPSIS
.B nfc-emulate-forum-tag2
.SH DESCRIPTION
.B nfc-emulate-forum-tag2
is a demonstration tool that emulates a NFC Forum tag type 2 that contains a read-only NDEF message.
.SH NOTES
It have been developed using PN533 USB hardware as target and Google Nexus S phone as initiator.

This is know to NOT work with Nokia 6212 Classic and could not work with several NFC Forum compliant devices due to these reasons:
   - The emulated target only have a 4 bytes UID where 7 bytes UID (as a real Mifare Ultralight tag) are usually attempted;
   - The chip is emulating a ISO/IEC 14443-3 tag, without any hardware helper.
   
If the initiator have too short timeouts for software-based emulation (which is usually the case), this example will failed, this is not a bug and we can't do anything using this kind of hardware (PN531/PN533).
.SH BUGS
Please report any bugs on the
.B libnfc
issue tracker at:
.br
.BR http://code.google.com/p/libnfc/issues
.SH LICENCE
.B libnfc
is licensed under the GNU Lesser General Public License (LGPL), version 3.
.br
.B libnfc-utils
and
.B libnfc-examples
are covered by the the BSD 2-Clause license.
.SH AUTHORS
Roel Verdult <roel@libnfc.org>, 
.br
Romain Tartière <romain@libnfc.org>, 
.br
Romuald Conty <romuald@libnfc.org>.
.PP
This manual page was written by Audrey Diacre <adiacre@il4p.fr>.
It is licensed under the terms of the GNU GPL (version 2 or later).