# - Try to find libusb or libusb-win32
# Once done this will define
#
#  LIBUSB_FOUND - True if libusb found
#  LIBUSB_INCLUDE_DIRS - The path to the libusb headers
#  LIBUSB_LIBRARY_DIRS - The path to the libusb library
#  LIBUSB_LIBRARIES - The libraries needed by libusb
#

FIND_PACKAGE(PkgConfig)
# Skip searching for libusb-0.1 on Windows, use libusb-win32 instead
IF(PKG_CONFIG_FOUND AND NOT WIN32)
  PKG_SEARCH_MODULE(LIBUSB libusb libusb-0.1)
  PKG_CHECK_MODULES(LIBUSB ${LIBUSB_MODULE_NAME})
ENDIF(PKG_CONFIG_FOUND AND NOT WIN32)

IF(NOT LIBUSB_FOUND)
  FIND_PATH(LIBUSB_INCLUDE_DIRS NAMES usb.h lusb0_usb.h)
  FIND_LIBRARY(LIBUSB_LIBRARIES NAMES libusb libusb0)
  GET_FILENAME_COMPONENT(LIBUSB_LIBRARY_DIRS ${LIBUSB_LIBRARIES} PATH CACHE)
ENDIF(NOT LIBUSB_FOUND)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBUSB REQUIRED_VARS
  LIBUSB_INCLUDE_DIRS
  LIBUSB_LIBRARIES
  LIBUSB_LIBRARY_DIRS
)
MARK_AS_ADVANCED(LIBUSB_INCLUDE_DIRS LIBUSB_LIBRARIES LIBUSB_LIBRARY_DIRS)
